version: "3"

services:
  texlive-ja:
    build: .
    environment:
      SHELL: "/bin/bash"
    command: sleep infinity
    platform: linux/amd64
    volumes:
      - ../:/workdir
      - ../.latexmkrc:/root/.latexmkrc
